language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - openssl aes-256-cbc -K $encrypted_3624fc9aaf00_key -iv $encrypted_3624fc9aaf00_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host 93.179.98.230\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g && gulp  #生成

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 27935' public/ git@www.yanglangjing.com:/var/www/blog
  - cd ./public
  - git config user.name "redanula"  #修改name
  - git config user.email "yanglangjing@hotmail.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${HEXO_TOKEN}@${GH_REF}" master:master  #HEXO_TOKEN是在Travis中配置token的名称

branches:
  only:
    - master  #只监测master分支
env:
 global:
   - GH_REF: github.com/redanula/redanula.github.com.git  #设置GH_REF，注意更改yourname

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - yanglangjing@hotmail.com
  on_success: change
  on_failure: always

# # 使用语言
# language: node_js
# # node版本
# node_js: stable
# # 设置只监听哪个分支
# branches:
#   only:
#   - source
# # 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
# cache:
#   apt: true
#   yarn: true
#   directories:
#     - node_modules
# # tarvis生命周期执行顺序详见官网文档
# before_install:
# - git config --global user.name "redanula"
# - git config --global user.email "yanglangjing@hotmail.com"
# # 由于使用了yarn，所以需要下载，如不用yarn这两行可以删除
# - curl -o- -L https://yarnpkg.com/install.sh | bash
# - export PATH=$HOME/.yarn/bin:$PATH
# - npm install -g hexo-cli
# install:
# # 不用yarn的话这里改成 npm i 即可
# - yarn
# script:
# - hexo clean
# - hexo generate
# after_success:
# - cd ./public
# - git init
# - git add --all .
# - git commit -m "Travis CI Auto Builder"
# # 这里的 HEXO_TOKEN 即之前在 travis 项目的环境变量里添加的
# - git push --quiet --force https://$HEXO_TOKEN@github.com/redanula/redanula.github.com.git
#  master
