language: node_js
node_js: stable
cache:
  apt: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_598a070685f0_key -iv $encrypted_598a070685f0_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- export TZ='Asia/Shanghai'
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 93.179.98.230\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
script:
- hexo clean
- hexo g && gulp
after_script:
- git clone https://${GH_REF} .deploy_git
- cd .deploy_git
- git checkout master
- cd ../
- mv .deploy_git/.git/ ./public/
- rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 27935' public/ git@www.yanglangjing.com:/var/www/blog
- cd ./public
- git config user.name "redanula"
- git config user.email "yanglangjing@hotmail.com"
- git add .
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
- git push --force --quiet "https://${HEXO_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/redanula/redanula.github.com.git
notifications:
  email:
  - yanglangjing@hotmail.com
  on_success: change
  on_failure: always
